Add fragmentation strategies for dataset summary generation
SolidBench/rdf-dataset-fragmenter.js pull request #18
Opened 2024-02-08 15:34 UTC by surilindur

This is an initial draft pull request for adding fragmentation strategies that will generate dataset summaries using the VoID vocabulary and the custom membership filter vocabulary for Bloom filters. The PR includes the following changes:

* Added `DatasetSummary` classes for VoID description and Bloom filters.
* Added `FragmentationStrategyDatasetSummary` for VoID description and Bloom filters, that collect descriptions for datasets and serialize them when flushed.
* Added instructions/explanation for the new fragmentation strategies in the readme.

The following other changes are also included, but I can try to move them to another PR if they feel unrelated:

* Updated the GitHub Actions to new versions, because the old ones used a deprecated Node version.
* Updated to version 2 of `@rubensworks/eslint-config`, fixed the linter errors associated with the update, and added the relevant rule exceptions in ESLint config. Also replaced exec with test for regular expression testing because it seems to be supported by all the relevant Node versions.
* Added a cast from readable-stream's own Readable to Node's own in the file loader, because the fragmenter uses Node's own streams whereas rdf-parse uses those from readable-stream.
* Replaced `npm` with `yarn` in the scripts of package.json, to allow the scripts to run without having to have the NPM CLI installed.

Any feedback is welcome! I will keep this as a draft until everything has been fixed.

2024-02-09 08:07 UTC, rubensworks commented
At first glance, this looks pretty good, nice work @surilindur!

However, as you suggested, it would be better to have the repo cleanup stuff (like linting) moved to a separate PR.
It makes it quite difficult to review the changes otherwise.
Could you look into that?
We could either first have the cleanup PR, and then the additions, or the other way around, that's up to you.

In any case, I would wait with merging the summary additions PR until we know for certain that @constraintAutomaton's shapes will fit into this framework as well.

2024-02-13 09:29 UTC, surilindur commented
The PR has been split now, but I noticed there is an error in the way the vocabulary is used for the Bloom filters. I will fix it before converting this into not-a-draft PR.

2024-02-13 14:36 UTC, surilindur commented
This is now rebased on the work in #20 because it helps make development easier

2024-02-15 10:19 UTC, surilindur commented
This still needs some fixes for the use of the membership vocabulary, I just noticed... :sob: I will also keep this as a draft until the shape generation has been tested to work with the same idea.

2024-02-15 10:21 UTC, rubensworks commented
Ok, no rush! :-)

2024-03-04 16:10 UTC, surilindur commented
This should be ready for review whenever there is time for it. I managed to set up the benchmarks using the branch from the fork, so there is no hurry.

2024-03-19 13:53 UTC, rubensworks requested changes
Good stuff! No major comments, besides two minor ones.

2024-03-19 13:53 UTC, rubensworks commented on README.md
> +#### Dataset Summary Fragmentation Strategies
Could we have 2 subsections here, one for VoID and one for Bloom?

2024-03-19 13:53 UTC, rubensworks commented on test/unit/strategy/FragmentationStrategyDatasetSummaryVoID-test.ts
> +// Jest.mock('../../../lib/io/ParallelFileWriter');
This can go?

2024-05-02 13:13 UTC, surilindur commented
This is now ready for review again! I have tested that it works with SolidBench.

2024-05-02 16:01 UTC, merged

2024-05-02 16:03 UTC, rubensworks commented
Thanks! Released as 2.7.0.