Add QuadTransformerDistributeIri
SolidBench/rdf-dataset-fragmenter.js pull request #21
Opened 2024-02-20 10:55 UTC by wvdemeer

A quad transformer that distributes IRIs over multiple destination IRIs. It does so by interpreting the first capture group as a number and using `replacementStrings[number % replacementStrings.length]`

(credit @twalcari)

2024-02-21 07:28 UTC, rubensworks requested changes
Thanks, looks great!

Could you also add a brief README entry on this with an example and description of how this new transformer can be used?

2024-02-21 07:28 UTC, rubensworks commented on lib/transform/QuadTransformerDistributeIri.ts
> +        const nr = Number.parseInt(match[1], 10);
Here we assume that the regex will only match numbers, but the user _could_ also provide a regex that matches strings.
I'd suggest adding a try-catch around this to check for number parsing failures, and re-throw a new error saying that the user provided an unexpected regex that matches non-numbers.
Additionally, we should also document this number-matching requirement on the regex.

2024-02-21 09:55 UTC, wvdemeer commented
Added info to `README.md`, and added clear errors to `QuadTransformerDistributeIri.transformTerm`.
Let me know if there's anything else that needs to be changed.

2024-02-22 06:55 UTC, rubensworks commented on lib/transform/QuadTransformerDistributeIri.ts
> +              `of which the first group must match a number.`);
```suggestion
          throw new Error(`'searchRegex' did not contain any groups, while QuadTransformerDistributeIri requires at least one group-based replacement, of which the first group must match a number.`);
```

2024-02-22 06:56 UTC, rubensworks commented on lib/transform/QuadTransformerDistributeIri.ts
> +              ` must always match a number, but it matched "${match[1]}" instead.`);
```suggestion
          throw new Error(`The first capture group in 'searchRegex' must always match a number, but it matched "${match[1]}" instead.`);
```

2024-02-22 06:56 UTC, rubensworks commented
Thanks for the update!

Could you add unit tests for those two error cases? (The CI required 100% test coverage)

2024-02-22 11:44 UTC, wvdemeer commented
100% test coverage now.

2024-02-23 07:41 UTC, merged

2024-02-23 07:41 UTC, rubensworks commented
Nice, thanks @wvdemeer!